### ISSUE TITLE
Cant Tame bc of Limit but dont have any Dog

### ISSUE THREAD

**Issue by NimaWood** [HeroGamers/MyDog#105]
### Type of bug

Other unexpected behaviour

### Bug description

![image](https://github.com/HeroGamers/MyDog/assets/96501660/d1ad6d5f-d265-492a-b21a-604a55a7ba4d)

### Steps to reproduce

1. Get bone
2. Tame dog

### Expected behaviour

get dog

### Actual behaviour

no dog

**Comment by HeroGamers** [comment]
What permissions do you have?

MyDog only gives this message if you have the permission `mydog.limit.0`. Do you have the permission `*.*.*`? If so, try denying the permission `mydog.limit.*`.
https://github.com/HeroGamers/MyDog/blob/master/src/main/java/dk/fido2603/mydog/managers/DogManager.java#LL131C70-L131C82

**Comment by HeroGamers** [comment]
I will close this issue until further information is provided.
