### ISSUE TITLE
Dogs cannot go through Nether Portals

### ISSUE THREAD

**Issue by Mikkel136** [HeroGamers/MyDog#119]
### Type of bug

Other unexpected behaviour

### Bug description

Dogs cannot travel to The Nether/The End by going through portals.

The only way to transport dogs through the Nether is by either
1. Putting them in a Minecart, and pushing that through a Nether Portal
2. Using /dog comehere [ID]

### Steps to reproduce

1. Be on the latest version of Paper for 1.21
2. Place a Nether Portal and stand on top of it
3. Dog wanders through the Nether Portal

### Expected behaviour

Dogs immediately travel through portals like other entities

### Actual behaviour

Dog do not travel through portals

**Comment by HeroGamers** [comment]
This is intentional behavior, as the dogs should always follow their owner, and not get pushed into portals and disappear.
https://github.com/HeroGamers/MyDog/blob/df7c2bc7fa3e59cb6df2ccdea04bddaa2fcc8d10/src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java#L539
