### ISSUE TITLE
Players can't tame dogs even when they dont have any

### ISSUE THREAD

**Issue by Ninja1986** [HeroGamers/MyDog#121]
### Type of bug

Other unexpected behaviour

### Bug description

Players can't tame a dog even with permissions on luck perms mydog.all.* perm in place

### Steps to reproduce

![{6A767635-B596-448A-B4D3-628AE898D037}](https://github.com/user-attachments/assets/599af0e5-04f0-456d-8a27-ead534a2542c)

### Expected behaviour

dogs to be tamed

### Actual behaviour

players are unable to tame dogs.

**Comment by HeroGamers** [comment]
I think you forgot to upload the permissions?

But take a look at https://github.com/HeroGamers/MyDog/issues/112 and https://github.com/HeroGamers/MyDog/issues/105

If it's not a duplicate issue, feel free to reply to reopen the issue, with permissions attached.
