### ISSUE TITLE
Command idea: /mydog sit <id|all>

### ISSUE THREAD

**Issue by d-513** [HeroGamers/MyDog#22]
it would make a specific doggo sit down, or you could use `/mydog sit all` to make all of them sit, for example if you have a lot of doggos but dont want them to disrupt you when you are building

**Comment by HeroGamers** [comment]
Hi there!

Thanks for the issue - I've not had the time to look at MyDog for quite some time, as I've been busy working on other projects. I've added the idea to the To-Do list, and will get onto working on it whenever I have some time to do so 👍 

Cheers,
Hero
