### ISSUE TITLE
Transfering dog ownership // Trade dogs

### ISSUE THREAD

**Issue by HeroGamers** [HeroGamers/MyDog#28]
Suggestion by hrzn00 on Spigot

**Comment by Tikkle** [comment]
Would love to see this implemented in your next update if possible, had a few players request this feature :)

**Comment by HeroGamers** [comment]
And it looks quite easy to implement as well - I just don't currently have that much time on my hands, sorry. Will get around to the features whenever I do though, but have no ETA.
