### ISSUE TITLE
Add configurable limit for amount of dogs

### ISSUE THREAD

**Issue by HeroGamers** [HeroGamers/MyDog#40]
Feature suggested by DrewBairres on SpigotMC.

**Comment by HeroGamers** [comment]
#70 “I want to set the maximum number of puppies per user rank.”

So I guess one could also add permissions for such things, to permit such usages.

For example, mydog.limit.10 or mydog.limit.20, etc.

**Comment by Bunnky** [comment]
This is something we're looking for as well.
