### ISSUE TITLE
Expand commands to call/affect all dogs

### ISSUE THREAD

**Issue by TimothyJCowen** [HeroGamers/MyDog#51]
It would be great to be able to type `/mydogs comehere` or `/mydogs comehere all`, and have all of your dogs teleport to you at once.

**Comment by HeroGamers** [comment]
From #71 :

Command all puppies at once
- Everyone sit down!
- Everyone stand up!
- Everyone, come here!
- Everyone hide! (Processing so that it is not visible on the screen)

So basically the same thing, but for the other commands as well.
