### ISSUE TITLE
Heal dog on kill (life-steal kinda)

### ISSUE THREAD

**Issue by HeroGamers** [HeroGamers/MyDog#59]

**Comment by Igzak** [comment]
Its feature can be made if the player has mcmmo plugin, so maybe make this togglable for those who use mcmmo

**Comment by HeroGamers** [comment]
Oh, I haven't had that enabled before with McMMO, is that a new feature? But thanks a lot - will definitely need a toggle for it then - since a lot of people use McMMO (but also I don't want to rely on "use *x* plugin if you'd want this feature".

**Comment by HeroGamers** [comment]
Lifesteal is effectively disabled when setting lifesteal to 0.
