### ISSUE TITLE
I would like to request 3 features.

### ISSUE THREAD

**Issue by excaliburkim** [HeroGamers/MyDog#69]
Thanks for making this program.
I am using it very well.

I would like to request 3 features.

1. I want to set the maximum number of puppies per user rank.
2. Command all puppies at once
     - Everyone sit down!
     - Everyone stand up!
     - Everyone, come here!
     - Everyone hide! (Processing so that it is not visible on the screen)
3. Give AMDIN permission to attack puppies.

**Comment by HeroGamers** [comment]
Could you please create an issue for each feature request? Thanks for taking your time to write them!
