### ISSUE TITLE
NO RELEASES

### ISSUE THREAD

**Issue by nunavailabul** [HeroGamers/MyDog#73]
"releases" is empty, links from spigot 404ing

**Comment by nunavailabul** [comment]
hmm I logged in and went back and now it's fine?  I have no idea.  TY for puppies.

**Comment by HeroGamers** [comment]
Hmm, I think I know why. The release on Spigot links to the old repo (DoggyCraft/MyDog), and I moved the repo to my private account, so the release is no longer there.
Will do a rerelease with the new link, thanks!
