### ISSUE TITLE
Console error when dogs teleport with Player

### ISSUE THREAD

**Issue by cubilization** [HeroGamers/MyDog#76]
Getting these errors when Dogs teleport with player (ie. When player types /home and dogs follow)

https://pastebin.com/3nm4kPf1

**Comment by HeroGamers** [comment]
I found this bug which got fixed on Paper, but I might try and see if I can reproduce it myself too, and possibly add a fix for it in MyDog, not depending on the server used.
Is it possible that the dog was dead or died?

https://github.com/PaperMC/Paper/issues/5380

**Comment by cubilization** [comment]
Hello,

The dog was alive, it doesn't affect the game or cause any issues but it just shows that error in console
Using Paper 1.19.3 / with no other plugins for pets/animal related
