### ISSUE TITLE
Dead list/ Remove a dog entry.

### ISSUE THREAD

**Issue by Yoltzyy** [HeroGamers/MyDog#77]
I added this to my server recently and have a couple issues. 1 being that dead dogs dont appear in the dead dog list. This making it no possible to revive a dead dog. Also id like to ask if adding a command to remove a dog from either list using the dogs id would be possible, as they end up stacking over time and maybe you dont want a list of 20+ dogs when you only have like 5.

**Comment by HeroGamers** [comment]
You can remove dogs from the active dogs list by releasing them. I will check up on the dead dogs not appearing - did you enable reviving? Can you also post your logs?

**Comment by Yoltzyy** [comment]
> You can remove dogs from the active dogs list by releasing them. I will check up on the dead dogs not appearing - did you enable reviving? Can you also post your logs?

the revival is on by default in configs, how do i get logs?

**Comment by HeroGamers** [comment]
In the config you can enable debug, and the logs are just your server logs from when the error happened.

**Comment by Yoltzyy** [comment]
[2023-02-03-1.log.gz](https://github.com/HeroGamers/MyDog/files/10578072/2023-02-03-1.log.gz)
heres the logs, i had to recreate because im not sure what logs theyd be in and im also not sure how to open them to check. i should add that the ComeHere command also doesnt work.

**Comment by HeroGamers** [comment]
These logs just shows you shutting down the server. If possible, could you enable `debug` in the MyDog config, and kill a dog, to see if it errors out, or throws anything in the console?

**Comment by Yoltzyy** [comment]
> These logs just shows you shutting down the server. If possible, could you enable `debug` in the MyDog config, and kill a dog, to see if it errors out, or throws anything in the console?
My bad, i sent the wrong log file, this one here shows the info you need im pretty sure. I had the debug on and i killed a dog or 2.
[2023-02-03-2.log](https://github.com/HeroGamers/MyDog/files/10582789/2023-02-03-2.log)

**Comment by HeroGamers** [comment]
I'll take a look at it sometime, but just from my immediate thoughts, it doesn't look like MyDog errors out, but you might have a conflicting plugin.
You could try putting MyDog on a test server (without any other plugins) and doing the same.

**Comment by Bunnky** [comment]
The only way to fix this issue I've found is to delete the "dead/unable to be located" dog IDs in `dogs.yml`. Runnin 1.19.3 latest plugin version, we're having the same issue.
